feat: 청구 상세 조회 페이지
Try-AngIe/cms-plus pull request #113
Opened 2024-07-20 10:40 UTC by pogihae

## TYPE
- [x] ✅ Feat
- [ ] 🔧 Fix
- [ ] ✨ Style
- [ ] 📖 Test
- [ ] 📝 Refactor
- [ ] 📈 Perf
- [ ] 📂 Docs
- [ ] 🅱 Build
- [ ] 🔄 CI

## DESCRIPTION
- 청구 상세 조회
- 청구 상태에 따른 가능 버튼 랜더링

## ISSUE
- [KAN-205]

2024-07-20 11:32 UTC, rlatkd approved these changes
good

2024-07-21 06:49 UTC, hyo-nu requested changes

2024-07-21 06:49 UTC, hyo-nu commented on client/src/apis/billing.js
> +    console.log('청구 수정 실패 => ', err.response);
log -> error로 변경 부탁드립니다~

2024-07-21 06:49 UTC, hyo-nu commented on client/src/components/common/inputs/InputWeb.jsx
> +      )}
labelEnabled를 따로 안주고 label 자체를 조건으로 사용하는것도 가능할까요??

2024-07-21 06:49 UTC, hyo-nu commented on client/src/components/common/inputs/InputWeb.jsx
> +      )}
그리고 label자체에 아무 값을 주지 않으면 label이 아마 나오지 않을 것 같습니다! 저도 그렇게 사용하고 있습니다!

2024-07-21 06:49 UTC, hyo-nu commented on client/src/components/vendor/billing/BillingDetailProduct.jsx
> +];
여기 그냥 둘까 했는데, 
utils / tableElements 위치에 billingProductElement.js로 따로 뺼까요??

2024-07-21 06:49 UTC, hyo-nu commented on client/src/utils/formatDate.js
> +};
굉장히 좋습니다!

2024-07-21 06:52 UTC, pogihae commented on client/src/apis/billing.js
> +    console.log('청구 수정 실패 => ', err.response);
감사합니다!

2024-07-21 06:52 UTC, pogihae commented on client/src/components/common/inputs/InputWeb.jsx
> +      )}
다시 롤백했습니다!

2024-07-21 06:55 UTC, pogihae commented on client/src/components/vendor/billing/BillingDetailProduct.jsx
> +];
넵!

2024-07-21 07:05 UTC, merged