feat: 상품을 수정/삭제할 수 있다.
Try-AngIe/cms-plus pull request #86
Opened 2024-07-13 13:45 UTC by rlatkd

## TYPE
- [ ] ✅ Feat
- [ ] 🔧 Fix
- [ ] ✨ Style
- [ ] 📖 Test
- [ ] 📝 Refactor
- [ ] 📈 Perf
- [ ] 📂 Docs
- [ ] 🅱 Build
- [ ] 🔄 CI

## DESCRIPTION
- BE 상품 수정 기능 구현
- BE 상품 삭제 기능 구현

## ISSUE
- [KAN-163]
- [KAN-164]

2024-07-13 16:03 UTC, pogihae requested changes

2024-07-13 16:03 UTC, pogihae commented on server/src/main/java/kr/or/kosa/cmsplusmain/domain/product/service/ProductService.java
> +        product.delete();
BaseRepository에 deleteById 사용해도 좋을 것 같아요!

2024-07-14 00:51 UTC, hyo-nu approved these changes

2024-07-14 00:51 UTC, hyo-nu commented on client/src/apis/product.js
> +    const res = await publicAxios.post('/v1/vendor/product', productData);
컨벤션에 맞춰서 수정한거 좋습니다~

2024-07-14 00:51 UTC, hyo-nu commented on client/src/components/vendor/modal/ProductModal.jsx
>    const [productName, setProductName] = useState('');
혹시 이부분 또한 name, price, memo를 하나의 useState로 관리할 수 있는 로직이라면, 하나로 관리해도 좋을 것 같습니다!

2024-07-14 08:42 UTC, rlatkd commented on server/src/main/java/kr/or/kosa/cmsplusmain/domain/product/service/ProductService.java
> +        product.delete();
넵

2024-07-14 08:42 UTC, rlatkd commented on client/src/components/vendor/modal/ProductModal.jsx
>    const [productName, setProductName] = useState('');
아하~ 알겠습니다

2024-07-14 08:43 UTC, merged